import {
  BedrockRuntimeClient,
  InvokeModelCommand,
} from '@aws-sdk/client-bedrock-runtime';
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { randomUUID } from 'crypto';

const bedrockClient = new BedrockRuntimeClient({
  region: process.env.REGION || 'us-east-1',
});
const s3Client = new S3Client({ region: process.env.REGION || 'us-east-1' });

interface ImageGenerationRequest {
  prompt: string;
  negativePrompt?: string;
  model?: 'stability' | 'titan';
  width?: number;
  height?: number;
  cfgScale?: number;
  steps?: number;
}

interface LambdaEvent {
  body: string;
  requestContext: {
    authorizer: {
      claims: {
        sub: string;
        email: string;
      };
    };
  };
}

export const handler = async (event: LambdaEvent) => {
  console.log('Event:', JSON.stringify(event, null, 2));

  try {
    // Parse request body
    const request: ImageGenerationRequest = JSON.parse(event.body);
    const { prompt, negativePrompt, model = 'stability', width = 512, height = 512, cfgScale = 7, steps = 50 } = request;

    // Get user info from Cognito claims
    const userId = event.requestContext.authorizer.claims.sub;
    const userEmail = event.requestContext.authorizer.claims.email;

    console.log(`Generating image for user: ${userEmail}`);

    // Generate image based on model
    let base64Image: string;
    let modelId: string;

    if (model === 'titan') {
      modelId = 'amazon.titan-image-generator-v1';
      base64Image = await generateImageWithTitan(prompt, negativePrompt, width, height);
    } else {
      modelId = 'stability.stable-diffusion-xl-v1';
      base64Image = await generateImageWithStability(prompt, negativePrompt, width, height, cfgScale, steps);
    }

    // Save to S3
    const imageKey = `${userId}/${randomUUID()}.png`;
    const bucketName = process.env.IMAGES_BUCKET_NAME!;

    await s3Client.send(
      new PutObjectCommand({
        Bucket: bucketName,
        Key: imageKey,
        Body: Buffer.from(base64Image, 'base64'),
        ContentType: 'image/png',
        Metadata: {
          userId: userId,
          userEmail: userEmail,
          prompt: prompt,
          model: modelId,
          generatedAt: new Date().toISOString(),
        },
      })
    );

    console.log(`Image saved to S3: ${bucketName}/${imageKey}`);

    // Return response
    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Credentials': true,
      },
      body: JSON.stringify({
        success: true,
        imageKey: imageKey,
        imageUrl: `https://${bucketName}.s3.${process.env.REGION}.amazonaws.com/${imageKey}`,
        model: modelId,
        prompt: prompt,
      }),
    };
  } catch (error) {
    console.error('Error generating image:', error);
    return {
      statusCode: 500,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Credentials': true,
      },
      body: JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
      }),
    };
  }
};

async function generateImageWithStability(
  prompt: string,
  negativePrompt?: string,
  width: number = 512,
  height: number = 512,
  cfgScale: number = 7,
  steps: number = 50
): Promise<string> {
  const modelId = 'stability.stable-diffusion-xl-v1';

  const payload = {
    text_prompts: [
      { text: prompt, weight: 1 },
      ...(negativePrompt ? [{ text: negativePrompt, weight: -1 }] : []),
    ],
    cfg_scale: cfgScale,
    steps: steps,
    seed: Math.floor(Math.random() * 1000000),
    width: width,
    height: height,
  };

  console.log('Invoking Stability model with payload:', JSON.stringify(payload));

  const command = new InvokeModelCommand({
    modelId: modelId,
    contentType: 'application/json',
    accept: 'application/json',
    body: JSON.stringify(payload),
  });

  const response = await bedrockClient.send(command);
  const responseBody = JSON.parse(new TextDecoder().decode(response.body));

  console.log('Stability model response:', JSON.stringify(responseBody));

  if (!responseBody.artifacts || responseBody.artifacts.length === 0) {
    throw new Error('No image generated by Stability model');
  }

  return responseBody.artifacts[0].base64;
}

async function generateImageWithTitan(
  prompt: string,
  negativePrompt?: string,
  width: number = 512,
  height: number = 512
): Promise<string> {
  const modelId = 'amazon.titan-image-generator-v1';

  const payload = {
    taskType: 'TEXT_IMAGE',
    textToImageParams: {
      text: prompt,
      ...(negativePrompt && { negativeText: negativePrompt }),
    },
    imageGenerationConfig: {
      numberOfImages: 1,
      quality: 'standard',
      width: width,
      height: height,
      cfgScale: 8.0,
      seed: Math.floor(Math.random() * 1000000),
    },
  };

  console.log('Invoking Titan model with payload:', JSON.stringify(payload));

  const command = new InvokeModelCommand({
    modelId: modelId,
    contentType: 'application/json',
    accept: 'application/json',
    body: JSON.stringify(payload),
  });

  const response = await bedrockClient.send(command);
  const responseBody = JSON.parse(new TextDecoder().decode(response.body));

  console.log('Titan model response:', JSON.stringify(responseBody));

  if (!responseBody.images || responseBody.images.length === 0) {
    throw new Error('No image generated by Titan model');
  }

  return responseBody.images[0];
}
