AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route53 Hosted Zone for hogehoge.com with DNS records'

Parameters:
  DomainName:
    Type: String
    Description: 'Domain name for the hosted zone'
    Default: 'hogehoge.com'
    AllowedValues:
      - 'hogehoge.com'

  DefaultTTL:
    Type: Number
    Description: 'Default TTL for DNS records (5min/1hour/24hours)'
    Default: 300
    AllowedValues:
      - 300    # 5分
      - 3600   # 1時間
      - 86400  # 24時間

Resources:
  # ホストゾーン
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub 'Public hosted zone for ${DomainName}'
      HostedZoneTags:
        - Key: Name
          Value: !Ref DomainName
        - Key: ManagedBy
          Value: CloudFormation

  # wwww1サブドメインのAレコード
  WWWW1ARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Sub 'wwww1.${DomainName}'
      Type: A
      TTL: !Ref DefaultTTL
      ResourceRecords:
        - '192.168.1.1'

Outputs:
  HostedZoneId:
    Description: 'Hosted Zone ID'
    Value: !Ref HostedZone
    Export:
      Name: 'hogehoge-com-HostedZoneId'

  HostedZoneName:
    Description: 'Hosted Zone Name'
    Value: !Ref DomainName
    Export:
      Name: 'hogehoge-com-HostedZoneName'

  NameServers:
    Description: 'Name servers - Update these at your domain registrar'
    Value: !Join [', ', !GetAtt HostedZone.NameServers]

  NameServer1:
    Description: 'Name Server 1'
    Value: !Select [0, !GetAtt HostedZone.NameServers]

  NameServer2:
    Description: 'Name Server 2'
    Value: !Select [1, !GetAtt HostedZone.NameServers]

  NameServer3:
    Description: 'Name Server 3'
    Value: !Select [2, !GetAtt HostedZone.NameServers]

  NameServer4:
    Description: 'Name Server 4'
    Value: !Select [3, !GetAtt HostedZone.NameServers]
