AWSTemplateFormatVersion: '2010-09-09'
Description: Storage Stack - S3 Buckets, DynamoDB Tables

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, stg, prod]
  SystemName:
    Type: String
    Default: system-a

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${SystemName}-${Environment}-data-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref Environment

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${SystemName}-${Environment}-logs-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: !If [IsProd, 365, 30]
      Tags:
        - Key: Environment
          Value: !Ref Environment

  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${SystemName}-${Environment}-app-table'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Outputs:
  DataBucketName:
    Value: !Ref DataBucket
    Export:
      Name: !Sub '${SystemName}-${Environment}-DataBucket'
  LogBucketName:
    Value: !Ref LogBucket
    Export:
      Name: !Sub '${SystemName}-${Environment}-LogBucket'
  AppTableName:
    Value: !Ref AppTable
    Export:
      Name: !Sub '${SystemName}-${Environment}-AppTable'
