AWSTemplateFormatVersion: '2010-09-09'
Description: Compute Stack - Lambda Functions, API Gateway

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, stg, prod]
  SystemName:
    Type: String
    Default: system-a

Resources:
  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${SystemName}-${Environment}-api'
      Runtime: python3.12
      Handler: index.handler
      Role:
        Fn::ImportValue: !Sub '${SystemName}-${Environment}-LambdaRoleArn'
      Code:
        ZipFile: |
          import json
          def handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps({'message': 'Hello from Lambda!'})
              }
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DATA_BUCKET:
            Fn::ImportValue: !Sub '${SystemName}-${Environment}-DataBucket'
      Timeout: 30
      MemorySize: !If [IsProd, 512, 256]
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${SystemName}-${Environment}-api'
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST

  ApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ApiFunction.Arn
      PayloadFormatVersion: '2.0'

  ApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: 'GET /api'
      Target: !Sub 'integrations/${ApiIntegration}'

  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGateway
      StageName: !Ref Environment
      AutoDeploy: true

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Outputs:
  ApiEndpoint:
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${SystemName}-${Environment}-ApiEndpoint'
  ApiFunctionArn:
    Value: !GetAtt ApiFunction.Arn
    Export:
      Name: !Sub '${SystemName}-${Environment}-ApiFunctionArn'
