AWSTemplateFormatVersion: '2010-09-09'
Description: Monitoring Stack - CloudWatch Alarms, Dashboard

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, stg, prod]
  SystemName:
    Type: String
    Default: system-a
  AlarmEmail:
    Type: String
    Default: ''

Conditions:
  CreateAlarmTopic: !Not [!Equals [!Ref AlarmEmail, '']]
  IsProd: !Equals [!Ref Environment, prod]

Resources:
  AlarmTopic:
    Type: AWS::SNS::Topic
    Condition: CreateAlarmTopic
    Properties:
      TopicName: !Sub '${SystemName}-${Environment}-alarms'

  AlarmSubscription:
    Type: AWS::SNS::Subscription
    Condition: CreateAlarmTopic
    Properties:
      TopicArn: !Ref AlarmTopic
      Protocol: email
      Endpoint: !Ref AlarmEmail

  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${SystemName}-${Environment}-lambda-errors'
      AlarmDescription: Lambda function errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Sub '${SystemName}-${Environment}-api'
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: !If [IsProd, 1, 5]
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !If [CreateAlarmTopic, !Ref AlarmTopic, !Ref 'AWS::NoValue']

  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${SystemName}-${Environment}-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0, "y": 0, "width": 12, "height": 6,
              "properties": {
                "title": "Lambda Invocations",
                "metrics": [
                  ["AWS/Lambda", "Invocations", "FunctionName", "${SystemName}-${Environment}-api"]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 12, "y": 0, "width": 12, "height": 6,
              "properties": {
                "title": "Lambda Errors",
                "metrics": [
                  ["AWS/Lambda", "Errors", "FunctionName", "${SystemName}-${Environment}-api"]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}"
              }
            }
          ]
        }

Outputs:
  DashboardUrl:
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${SystemName}-${Environment}-dashboard'
